# backend/Dockerfile
# 1. Builder stage (install dependencies)
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci --only=production

# 2. Final stage
FROM node:18-alpine
WORKDIR /app

# Copy prod deps
COPY --from=build /app/node_modules ./node_modules
# Copy application
COPY . .

# Expose and run
ENV PORT=5000
EXPOSE 5000
CMD ["node", "server.js"]
