apiVersion: apps/v1
kind: Deployment
metadata: { name: backend }
spec:
  replicas: 2
  selector: { matchLabels: { app: backend } }
  template:
    metadata: { labels: { app: backend } }
    spec:
      containers:
      - name: backend
        image: expense-tracker-backend:latest
        imagePullPolicy: IfNotPresent
        ports: [{ containerPort: 5000 }]
        resources:
          requests: { cpu: "100m", memory: "128Mi" }
          limits:   { cpu: "500m", memory: "512Mi" }
        envFrom:
        - configMapRef: { name: expense-config }
        - secretRef:    { name: expense-secrets }
